# Generated by Django 4.2.3 on 2023-07-18 16:38

import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0006_feedback_flagged_as_spam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="token",
            field=models.CharField(
                blank=True,
                default=feedback.models.generate_feedback_token,
                max_length=100,
            ),
        ),
    ]
