# Generated by Django 4.1.6 on 2023-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0014_localparty_created_localparty_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="date_deregistered",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="party",
            name="date_registered",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="party",
            name="ec_id",
            field=models.CharField(
                db_index=True,
                help_text="\n            An ID issued by The Electoral Commission in their party register,\n            with the exception of Democracy Club psuedo IDs for special parties\n        ",
                max_length=25,
                null=True,
                unique=True,
                verbose_name="Electoral Commission Idenfitier",
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="register",
            field=models.CharField(
                db_index=True,
                help_text="\n                Normally either `GB` or `NI` depending on the\n                country the party is registered in. Pseudo-parties don't have a\n                register, so this field is nullable.\n            ",
                max_length=2,
                null=True,
                verbose_name="Party register",
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="status",
            field=models.CharField(
                choices=[
                    ("Registered", "Registered"),
                    ("Deregistered", "Deregistered"),
                ],
                db_index=True,
                default="Registered",
                max_length=255,
                verbose_name="Party registration status",
            ),
        ),
    ]
