# Generated by Django 4.1.6 on 2023-04-20 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0017_partyemblem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partydescription",
            options={"ordering": ["date_description_approved"]},
        ),
    ]
