# Generated by Django 4.1.6 on 2023-06-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0019_alter_partydescription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="alternative_name",
            field=models.CharField(max_length=765, null=True),
        ),
    ]
