# Generated by Django 4.2.6 on 2023-11-20 09:23

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0045_person_delisted"),
        ("parties", "0021_party_nations"),
    ]

    operations = [
        migrations.CreateModel(
            name="PPCPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(blank=True, max_length=255)),
                ("constituency_name", models.CharField(max_length=255)),
                ("region_name", models.CharField(blank=True, max_length=255)),
                ("sheet_row", models.JSONField()),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parties.party",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.person",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "constituency_name",
                    core.utils.LastWord("person_name"),
                ),
            },
        ),
    ]
