# Generated by Django 4.1.6 on 2023-09-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0044_person_mastodon_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="delisted",
            field=models.BooleanField(default=False),
        ),
    ]
