# Generated by Django 4.2.10 on 2024-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0046_personpost_deselected_personpost_deselected_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="statement_to_voters_last_updated",
            field=models.DateTimeField(null=True),
        ),
    ]
