# Generated by Django 4.2.11 on 2024-05-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0048_person_blue_sky_url_person_other_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonRedirect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_person_id", models.IntegerField()),
                ("new_person_id", models.IntegerField()),
            ],
        ),
    ]
