# Generated by Django 4.2.6 on 2023-11-17 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auto_20210225_1103"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoggedPostcode",
        ),
    ]
