# Generated by Django 4.1.6 on 2023-03-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0039_remove_historic_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="postelection",
            name="requires_voter_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
