# Generated by Django 4.2.3 on 2023-09-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0040_postelection_requires_voter_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="ballot_papers_issued",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="electorate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="spoilt_ballots",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="election",
            name="turnout",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
