# Generated by Django 4.2.3 on 2023-09-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "elections",
            "0041_election_ballot_papers_issued_election_electorate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="postelection",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_CANDIDATES", "No candidates"),
                    ("EQUAL_CANDIDATES", "Equal candidates to seats"),
                    ("UNDER_CONTESTED", "Fewer candidates than seats"),
                    ("CANDIDATE_DEATH", "Death of a candidate"),
                ],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
    ]
