# Generated by Django 4.2.6 on 2023-10-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0042_postelection_cancellation_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="election",
            name="ballot_papers_issued",
        ),
        migrations.RemoveField(
            model_name="election",
            name="electorate",
        ),
        migrations.RemoveField(
            model_name="election",
            name="spoilt_ballots",
        ),
        migrations.RemoveField(
            model_name="election",
            name="turnout",
        ),
        migrations.AddField(
            model_name="postelection",
            name="ballot_papers_issued",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postelection",
            name="electorate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postelection",
            name="spoilt_ballots",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="postelection",
            name="turnout",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
