# Generated by Django 4.2.10 on 2024-03-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0043_remove_election_ballot_papers_issued_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="ee_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
